# Generated by Django 5.2 on 2025-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
